### ISSUE TITLE
Default to using box-sizing: border-box ?

### ISSUE THREAD

**Issue by jasonkuhrt** [suitcss/base#20]
I think this would be the best default for apps:

```css
* {
  box-sizing: border-box;
}
```

**Comment by simonsmith** [comment]
This seems like a sensible default, I manually add it to everything myself normally. I know that Bootstrap also perform the same reset on top of normalize:

``` css
html {
  box-sizing: border-box;
}

*,
*::before,
*::after {
  box-sizing: inherit;
}
```

cc @giuseppeg @timkelty
