### ISSUE TITLE
Redundant box-sizing content

### ISSUE THREAD

**Issue by oleersoy** [suitcss/base#30]
[Bootstrap 4's](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss) box-sizing inheritance block looks like this:
```css
*,
*::before,
*::after {
  box-sizing: inherit;
}
```
The one in base includes an addition input element.  I believe that the `*` selects that element.

**Comment by giuseppeg** [comment]
It was added because of https://github.com/suitcss/base/pull/29

**Comment by oleersoy** [comment]
Read up on it some more.  Itt may be wise to separate it out.  Bootstrap does it like this:
```css
input[type="search"] {
  // Undo Normalize's default here to match our global overrides.
  box-sizing: inherit;
  // This overrides the extra rounded corners on search inputs in iOS so that our
  // `.form-control` class can properly style them. Note that this cannot simply
  // be added to `.form-control` as it's not specific enough. For details, see
  // https://github.com/twbs/bootstrap/issues/11586.
  -webkit-appearance: none;
}
```
